### ISSUE TITLE
The test for AVX2 is broken: you need the ECX=0 sub-leaf of EAX=7

### ISSUE THREAD

**Issue by pcordes** [FastAsChuff/MD5-SIMD-Test#1]
Running on my Skylake (i7-6700k), the program reports 
`1730785267 : This program ./a.out requires AVX2 support.`

`__get_cpuid(7, &eax, &ebx, &ecx, &edx);` leaves whatever garbage was in ECX as the subleaf.  You need ECX=0 because that's where the AVX2 feature bit is.  (I tried setting the `ecx` C output variable to zero, but it's output-only.)

https://stackoverflow.com/questions/15276788/how-to-call-cpuid-leaf-7-and-subleaf-0 suggests `__get_cpuid_count` which lets you pass an ECX input as the second arg, with the 4 pointers following.

Technically you should also be checking xgetbv to make sure the OS has set that bit which lets AVX instructions run without faulting.  (OSes that don't know about AVX won't save/restore YMM regs on context switch, and won't set the bit, so AVX insns fault.  OSes that do know about AVX will context-switch properly and will set that bit. https://stackoverflow.com/questions/72522885/are-the-xgetbv-and-cpuid-checks-sufficient-to-guarantee-avx2-support)  But an OS would have to be pretty old, like pre 2010, not to support AVX, so you can probably get away without checking.

Or you could just use `__builtin_cpu_supports("avx2")`  https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/X86-Built-in-Functions.html .  Since GCC8, it checks for OS support as well, if you're using GNU C features anyway.  (I forget if `__get_cpuid` is portable to MSVC.)

**Comment by FastAsChuff** [comment]
Thanks for the heads up. I've just commented out the runtime check until I
have more time to come up with a better approach. I don't have any AVX2
supporting hardware, which is a bit sad I know. Time for an upgrade....

**Comment by pcordes** [comment]
You can test with Intel's SDE emulator.
